/**
 * Vertical configuration registry.
 * Add new verticals here — no code changes needed elsewhere.
 * All prompts, checklist items, and category weights are co-located.
 */

export const VERTICALS = {
  manufacturing: {
    label: "Machine Shop / Manufacturing",
    icon: "⚙️",
    documentTypes: [
      "work_order", "quote", "job_traveler", "purchase_order",
      "customer_list", "equipment_list", "qc_record", "financial",
    ],
    promptedQuestions: [
      "Walk me through how you quote a new job.",
      "Who are your three most important customers and why?",
      "What equipment would need to be replaced in the next 2 years?",
      "What breaks most often on the shop floor and how do you handle it?",
      "Who knows how to run every machine if you weren't there?",
      "Describe how a work order flows from sales to shipping.",
    ],
    associationPartners: ["NTMA", "PMPA", "AMT"],
    checklistItems: [
      { key: "customer_list",        category: "customers",   label: "Customer list extracted",           weight: 0.5 },
      { key: "multiple_customers",   category: "customers",   label: "3+ customers documented",           weight: 0.3 },
      { key: "top_customer_revenue", category: "customers",   label: "Revenue by customer on file",       weight: 0.2 },
      { key: "financials_present",   category: "financials",  label: "Financial records uploaded",        weight: 0.34 },
      { key: "two_year_financials",  category: "financials",  label: "2 years of P&L available",         weight: 0.33 },
      { key: "three_year_financials",category: "financials",  label: "3 years of P&L available",         weight: 0.33 },
      { key: "sops_present",         category: "operations",  label: "Core SOPs documented",              weight: 0.5 },
      { key: "multiple_sops",        category: "operations",  label: "3+ SOPs documented",                weight: 0.5 },
      { key: "equipment_list",       category: "equipment",   label: "Equipment list extracted",          weight: 0.6 },
      { key: "equipment_detail",     category: "equipment",   label: "Equipment ages/condition recorded", weight: 0.4 },
      { key: "key_personnel",        category: "people",      label: "Key personnel identified",          weight: 0.6 },
      { key: "org_chart",            category: "people",      label: "Org structure documented",          weight: 0.4 },
      { key: "certifications",       category: "compliance",  label: "ISO/QMS certifications uploaded",   weight: 0.6 },
      { key: "licenses",             category: "compliance",  label: "Business licenses on file",         weight: 0.4 },
    ],
  },

  hvac: {
    label: "HVAC / Mechanical",
    icon: "🌡️",
    documentTypes: [
      "service_agreement", "maintenance_contract", "equipment_list",
      "customer_list", "financial", "license", "certification",
    ],
    promptedQuestions: [
      "What percentage of your revenue is recurring maintenance contracts?",
      "How many service technicians do you have and what are their certifications?",
      "What are your top commercial accounts and how long have you had them?",
      "Describe your dispatch and scheduling process.",
      "What licenses do you hold and in which jurisdictions?",
      "How do you handle warranty and callback situations?",
    ],
    associationPartners: ["ACCA", "PHCC", "SMACNA"],
    checklistItems: [
      { key: "customer_list",        category: "customers",   label: "Customer list extracted",           weight: 0.5 },
      { key: "recurring_contracts",  category: "customers",   label: "Recurring maintenance contracts",   weight: 0.5 },
      { key: "financials_present",   category: "financials",  label: "Financial records uploaded",        weight: 0.5 },
      { key: "three_year_financials",category: "financials",  label: "3 years of P&L available",         weight: 0.5 },
      { key: "dispatch_sop",         category: "operations",  label: "Dispatch/scheduling process",       weight: 0.5 },
      { key: "service_sops",         category: "operations",  label: "Service SOPs documented",           weight: 0.5 },
      { key: "equipment_list",       category: "equipment",   label: "Fleet/equipment list",              weight: 0.5 },
      { key: "equipment_condition",  category: "equipment",   label: "Equipment condition recorded",      weight: 0.5 },
      { key: "technicians",          category: "people",      label: "Technician roster documented",      weight: 0.6 },
      { key: "certifications_people",category: "people",      label: "Tech certifications on file",       weight: 0.4 },
      { key: "state_license",        category: "compliance",  label: "State contractor license",          weight: 0.6 },
      { key: "epa_certification",    category: "compliance",  label: "EPA 608 certifications",            weight: 0.4 },
    ],
  },

  plumbing: {
    label: "Plumbing",
    icon: "🔧",
    documentTypes: [
      "service_agreement", "project_contract", "customer_list",
      "financial", "license", "equipment_list",
    ],
    promptedQuestions: [
      "What mix of residential vs commercial work do you do?",
      "Who are your best commercial/property management clients?",
      "How many licensed plumbers are on staff?",
      "What licenses do you hold and in which jurisdictions?",
      "Walk me through a typical service call from dispatch to invoice.",
      "How do you handle emergency calls and after-hours?",
    ],
    associationPartners: ["PHCC", "ACPA", "UA"],
    checklistItems: [
      { key: "customer_list",        category: "customers",   label: "Customer list extracted",           weight: 0.5 },
      { key: "commercial_accounts",  category: "customers",   label: "Commercial accounts documented",    weight: 0.5 },
      { key: "financials_present",   category: "financials",  label: "Financial records uploaded",        weight: 0.5 },
      { key: "three_year_financials",category: "financials",  label: "3 years of P&L available",         weight: 0.5 },
      { key: "dispatch_sop",         category: "operations",  label: "Service dispatch process",          weight: 0.5 },
      { key: "billing_sop",          category: "operations",  label: "Billing/invoicing process",         weight: 0.5 },
      { key: "truck_fleet",          category: "equipment",   label: "Truck/van fleet documented",        weight: 0.6 },
      { key: "tools",                category: "equipment",   label: "Tool inventory",                    weight: 0.4 },
      { key: "licensed_plumbers",    category: "people",      label: "Licensed plumbers identified",      weight: 0.7 },
      { key: "apprentices",          category: "people",      label: "Apprentice roster",                 weight: 0.3 },
      { key: "master_license",       category: "compliance",  label: "Master plumber license",            weight: 0.7 },
      { key: "bonding",              category: "compliance",  label: "Bond/insurance certificates",       weight: 0.3 },
    ],
  },

  electrical: {
    label: "Electrical Contracting",
    icon: "⚡",
    documentTypes: [
      "project_contract", "customer_list", "financial", "license",
      "certification", "equipment_list", "safety_record",
    ],
    promptedQuestions: [
      "What percentage of work is commercial vs residential vs industrial?",
      "Who are your largest commercial clients?",
      "How many journeymen and master electricians are on staff?",
      "What licenses do you hold across which states?",
      "Describe your safety record and OSHA compliance.",
      "What is your largest completed project?",
    ],
    associationPartners: ["IEC", "NECA", "IBEW"],
    checklistItems: [
      { key: "customer_list",        category: "customers",   label: "Customer list extracted",           weight: 0.5 },
      { key: "commercial_accounts",  category: "customers",   label: "Commercial project history",        weight: 0.5 },
      { key: "financials_present",   category: "financials",  label: "Financial records uploaded",        weight: 0.5 },
      { key: "three_year_financials",category: "financials",  label: "3 years of financials",             weight: 0.5 },
      { key: "project_sops",         category: "operations",  label: "Project management process",        weight: 0.5 },
      { key: "safety_sops",          category: "operations",  label: "Safety/OSHA procedures",            weight: 0.5 },
      { key: "equipment_list",       category: "equipment",   label: "Tools/equipment inventory",         weight: 0.6 },
      { key: "vehicles",             category: "equipment",   label: "Vehicle fleet documented",          weight: 0.4 },
      { key: "electricians",         category: "people",      label: "Licensed electricians identified",  weight: 0.7 },
      { key: "apprentices",          category: "people",      label: "Apprentice roster",                 weight: 0.3 },
      { key: "state_license",        category: "compliance",  label: "State electrical license",          weight: 0.6 },
      { key: "safety_record",        category: "compliance",  label: "OSHA safety record on file",        weight: 0.4 },
    ],
  },

  construction: {
    label: "General Construction",
    icon: "🏗️",
    documentTypes: [
      "project_contract", "subcontractor_agreement", "customer_list",
      "financial", "license", "bond", "equipment_list", "safety_record",
    ],
    promptedQuestions: [
      "What types of projects do you primarily take on?",
      "Who are your top 5 clients by revenue?",
      "What's your backlog look like today?",
      "How do you manage subcontractors?",
      "Describe your bonding capacity and current bond.",
      "What is your largest completed project and timeline?",
    ],
    associationPartners: ["AGC", "ABC", "NAHB"],
    checklistItems: [
      { key: "customer_list",        category: "customers",   label: "Client list extracted",             weight: 0.4 },
      { key: "project_history",      category: "customers",   label: "Project history documented",        weight: 0.4 },
      { key: "backlog",              category: "customers",   label: "Current backlog/pipeline",          weight: 0.2 },
      { key: "financials_present",   category: "financials",  label: "Financial records uploaded",        weight: 0.4 },
      { key: "three_year_financials",category: "financials",  label: "3 years of financials",             weight: 0.4 },
      { key: "wip_schedule",         category: "financials",  label: "WIP schedule available",            weight: 0.2 },
      { key: "project_sops",         category: "operations",  label: "Project management SOPs",           weight: 0.5 },
      { key: "sub_management",       category: "operations",  label: "Subcontractor management process",  weight: 0.5 },
      { key: "equipment_list",       category: "equipment",   label: "Heavy equipment list",              weight: 0.6 },
      { key: "vehicles",             category: "equipment",   label: "Vehicle fleet documented",          weight: 0.4 },
      { key: "project_managers",     category: "people",      label: "Project managers identified",       weight: 0.6 },
      { key: "field_supers",         category: "people",      label: "Field supervisors documented",      weight: 0.4 },
      { key: "gc_license",           category: "compliance",  label: "GC license on file",                weight: 0.5 },
      { key: "bonding",              category: "compliance",  label: "Surety bond documented",            weight: 0.5 },
    ],
  },

  trucking: {
    label: "Trucking / Freight",
    icon: "🚛",
    documentTypes: [
      "customer_list", "rate_agreement", "equipment_list",
      "financial", "dot_record", "insurance", "driver_record",
    ],
    promptedQuestions: [
      "How many power units are in your fleet?",
      "What lanes or regions do you primarily run?",
      "Who are your top 3 shippers by revenue?",
      "What is your driver turnover rate?",
      "Describe your DOT safety rating and compliance history.",
      "How do you manage maintenance scheduling?",
    ],
    associationPartners: ["ATA", "OOIDA", "TCA"],
    checklistItems: [
      { key: "customer_list",        category: "customers",   label: "Shipper list extracted",            weight: 0.5 },
      { key: "rate_agreements",      category: "customers",   label: "Rate agreements documented",        weight: 0.5 },
      { key: "financials_present",   category: "financials",  label: "Financial records uploaded",        weight: 0.5 },
      { key: "three_year_financials",category: "financials",  label: "3 years of financials",             weight: 0.5 },
      { key: "dispatch_sop",         category: "operations",  label: "Dispatch process documented",       weight: 0.5 },
      { key: "maintenance_sop",      category: "operations",  label: "Maintenance schedule process",      weight: 0.5 },
      { key: "power_units",          category: "equipment",   label: "Truck fleet documented",            weight: 0.5 },
      { key: "trailers",             category: "equipment",   label: "Trailer inventory on file",         weight: 0.5 },
      { key: "drivers",              category: "people",      label: "Driver roster documented",          weight: 0.7 },
      { key: "dispatchers",          category: "people",      label: "Dispatch/admin staff",              weight: 0.3 },
      { key: "dot_number",           category: "compliance",  label: "DOT number / authority",            weight: 0.5 },
      { key: "safety_rating",        category: "compliance",  label: "FMCSA safety rating documented",    weight: 0.5 },
    ],
  },

  agriculture: {
    label: "Agriculture / Farm",
    icon: "🌾",
    documentTypes: [
      "lease_agreement", "crop_history", "equipment_list",
      "financial", "certification", "customer_list", "soil_report",
    ],
    promptedQuestions: [
      "How many acres do you farm — owned vs leased?",
      "What crops do you grow and what are your typical yields?",
      "Who do you sell to — co-op, direct, processors?",
      "Describe your equipment fleet and condition.",
      "What certifications do you hold (organic, GAP, etc.)?",
      "How is the farm operated during peak seasons?",
    ],
    associationPartners: ["AFB", "NSAC", "NFU"],
    checklistItems: [
      { key: "customer_list",        category: "customers",   label: "Buyers/buyers list extracted",      weight: 0.5 },
      { key: "contracts",            category: "customers",   label: "Grain/sale contracts on file",      weight: 0.5 },
      { key: "financials_present",   category: "financials",  label: "Financial records uploaded",        weight: 0.5 },
      { key: "three_year_financials",category: "financials",  label: "3 years of farm financials",        weight: 0.5 },
      { key: "crop_plan",            category: "operations",  label: "Crop rotation plan documented",     weight: 0.5 },
      { key: "harvest_sop",          category: "operations",  label: "Harvest process documented",        weight: 0.5 },
      { key: "equipment_list",       category: "equipment",   label: "Farm equipment list",               weight: 0.6 },
      { key: "equipment_condition",  category: "equipment",   label: "Equipment condition/age recorded",  weight: 0.4 },
      { key: "operators",            category: "people",      label: "Operators/farmhands identified",    weight: 0.7 },
      { key: "seasonal_labor",       category: "people",      label: "Seasonal labor arrangement",        weight: 0.3 },
      { key: "land_lease",           category: "compliance",  label: "Land lease agreements on file",     weight: 0.5 },
      { key: "certifications",       category: "compliance",  label: "Organic/GAP certifications",        weight: 0.5 },
    ],
  },
} as const;

export type Vertical = keyof typeof VERTICALS;
export type VerticalConfig = typeof VERTICALS[Vertical];
