/**
 * Cloudflare Worker entry point.
 *
 * OpenNext generates `.open-next/worker.js` exporting only the Next.js `fetch`
 * handler. Durable Objects, Workflows, the Queue consumer, and the Email Worker
 * must be exported from the deployed Worker too — so this thin wrapper composes
 * them all and is referenced by `main` in wrangler.toml.
 *
 * Build order: `opennextjs-cloudflare build` produces `.open-next/worker.js`
 * before `wrangler deploy` bundles this file.
 *
 * Sentry: the default handler is wrapped with `@sentry/cloudflare`'s
 * `withSentry` so uncaught errors in the CF-native `fetch`/`queue`/`email`
 * paths (the parts the Next.js instrumentation hook does NOT see) are reported.
 * Next.js route errors are captured separately via src/instrumentation.ts.
 */

import { withSentry } from "@sentry/cloudflare";

// @ts-ignore — generated by `opennextjs-cloudflare build` at build time.
import openNextHandler from "./.open-next/worker.js";

import ingestConsumer from "./src/server/workers/ingest";
import { handleEmail, type EmailMessage, type EmailEnv } from "./src/server/workers/email-ingest";
import { runChurnCron, type ChurnEnv } from "./src/server/workers/churn-cron";

// Durable Objects and Workflows must be exported by name so the runtime can
// instantiate the classes referenced in wrangler.toml.
export { ProcessingStateDO, DealRoomDO } from "./src/server/durable-objects/processing-state";
export { DocumentPipeline } from "./src/workflows/document-pipeline";

// The worker receives one runtime env; the queue/email handlers narrow it to
// their own shapes (IngestEnv / EmailEnv). SENTRY_DSN is the secret read by
// withSentry's options callback.
type WorkerEnv = {
  SENTRY_DSN?: string;
  ENVIRONMENT?: string;
  DB?: D1Database;
  EMAIL?: { send: (m: unknown) => Promise<{ messageId?: string }> };
  EMAIL_FROM?: string;
  APP_URL?: string;
};

const handler = openNextHandler as {
  fetch: (req: Request, env: unknown, ctx: ExecutionContext) => Promise<Response>;
};

// Baseline security headers on every response. The CSP is deliberately
// conservative (unsafe-inline for Next's inlined scripts/styles, https: for
// Sentry + OSM tiles) — tighten per-directive once nonce support is wired.
const SECURITY_HEADERS: Record<string, string> = {
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  // Microphone stays enabled for same-origin: the Knowledge page records SOPs.
  "Permissions-Policy": "camera=(self), microphone=(self), geolocation=()",
  "Content-Security-Policy": [
    "default-src 'self'",
    "script-src 'self' 'unsafe-inline'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob: https:",
    "font-src 'self' data:",
    "connect-src 'self' https:",
    "media-src 'self' blob:",
    "worker-src 'self' blob:",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
  ].join("; "),
};

function withSecurityHeaders(res: Response): Response {
  // WebSocket upgrades can't be re-wrapped.
  if (res.status === 101) return res;
  const headers = new Headers(res.headers);
  for (const [k, v] of Object.entries(SECURITY_HEADERS)) {
    if (!headers.has(k)) headers.set(k, v);
  }
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers });
}

const composedHandler: ExportedHandler<WorkerEnv> = {
  async fetch(req: Request, env: WorkerEnv, ctx: ExecutionContext): Promise<Response> {
    // Redirect www → apex (301, path + query preserved) for clean canonical URLs.
    const url = new URL(req.url);
    if (url.hostname === "www.successio.pro") {
      url.hostname = "successio.pro";
      return Response.redirect(url.toString(), 301);
    }
    return withSecurityHeaders(await handler.fetch(req, env, ctx));
  },

  // Queue consumer (document-jobs) — delegates to the existing ingest handler.
  queue(batch, env) {
    return ingestConsumer.queue(batch, env as never);
  },

  // Email Worker — forward documents to the ingest pipeline.
  async email(message, env, _ctx): Promise<void> {
    await handleEmail(message as unknown as EmailMessage, env as unknown as EmailEnv);
  },

  // Churn prevention cron — runs on the schedule in wrangler.toml [triggers].
  async scheduled(_event: ScheduledController, env: WorkerEnv, ctx: ExecutionContext): Promise<void> {
    await runChurnCron(env as ChurnEnv, ctx);
  },
};

export default withSentry<WorkerEnv>(
  (env) => ({
    dsn: env.SENTRY_DSN,
    environment: env.ENVIRONMENT ?? "production",
    tracesSampleRate: 0.1,
    sendDefaultPii: false,
    initialScope: {
      tags: { app_slug: "successio", federation_phase: "pre-launch", tier: "worker" },
    },
  }),
  composedHandler,
);
