/**
 * Cloudflare Worker entry point.
 *
 * OpenNext generates `.open-next/worker.js` exporting only the Next.js `fetch`
 * handler. Durable Objects, Workflows, the Queue consumer, and the Email Worker
 * must be exported from the deployed Worker too — so this thin wrapper composes
 * them all and is referenced by `main` in wrangler.toml.
 *
 * Build order: `opennextjs-cloudflare build` produces `.open-next/worker.js`
 * before `wrangler deploy` bundles this file.
 */

// @ts-ignore — generated by `opennextjs-cloudflare build` at build time.
import openNextHandler from "./.open-next/worker.js";

import ingestConsumer from "./src/server/workers/ingest";
import { handleEmail, type EmailMessage, type EmailEnv } from "./src/server/workers/email-ingest";

// Durable Objects and Workflows must be exported by name so the runtime can
// instantiate the classes referenced in wrangler.toml.
export { ProcessingStateDO, DealRoomDO } from "./src/server/durable-objects/processing-state";
export { DocumentPipeline } from "./src/workflows/document-pipeline";

const handler = openNextHandler as {
  fetch: (req: Request, env: unknown, ctx: ExecutionContext) => Promise<Response>;
};

export default {
  async fetch(req: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {
    // Redirect www → apex (301, path + query preserved) for clean canonical URLs.
    const url = new URL(req.url);
    if (url.hostname === "www.successio.pro") {
      url.hostname = "successio.pro";
      return Response.redirect(url.toString(), 301);
    }
    return handler.fetch(req, env, ctx);
  },

  // Queue consumer (document-jobs) — delegates to the existing ingest handler.
  queue: ingestConsumer.queue,

  // Email Worker — forward documents to the ingest pipeline.
  async email(message: EmailMessage, env: EmailEnv, _ctx: ExecutionContext): Promise<void> {
    await handleEmail(message, env);
  },
};
