import { LegalPage } from "@/components/marketing/legal-page";

export const metadata = { title: "Terms of Service — Successio" };

const BODY = `
These Terms of Service ("Terms") govern your use of Successio (the "Service"), operated by Successio ("we", "us"). By creating an account or using the Service you agree to these Terms.

## 1. What the Service is — and is not

Successio is a **document-preparation and business-documentation tool**. It helps you organize records, capture operational knowledge, and generate descriptive materials about your business.

Successio is **not** a business broker, investment bank, law firm, accounting firm, or financial advisor. We do not introduce buyers and sellers, negotiate transactions, provide valuations, or receive any fee contingent on the sale of a business. Content generated by the Service — including readiness scores and business profiles — is informational only and is not legal, financial, tax, or investment advice. Engage licensed professionals for the sale of a business.

## 2. AI-generated content and accuracy

The Service uses artificial intelligence to read documents and draft summaries. AI output can contain errors, omissions, or mischaracterizations — including in extracted numbers.

- **You are responsible for reviewing and verifying all AI-generated content before relying on it or sharing it with any third party.** The Service provides review tools for exactly this purpose.
- We make no warranty that extracted data or generated profiles are accurate, complete, or fit for any particular purpose.

## 3. Your content

You retain ownership of everything you upload and create. You grant us a limited license to store, process (including with AI models), and display your content solely to operate the Service for you. We do not sell your content, and we do not use your business documents to train AI models.

You are responsible for having the right to upload what you upload — including any personal information about employees or customers contained in your documents — and for what you choose to share via share links.

## 4. Sharing features

Share links, the NDA gate, and access logs are convenience features. The NDA gate records a viewer's self-attested name, email, and agreement to confidentiality; **it is not a substitute for a negotiated, signed non-disclosure agreement** where one is warranted. You control what tier of information each link exposes, and you assume the risk of distributing links.

## 5. Acceptable use

Don't use the Service to violate the law, infringe others' rights, upload malicious files, probe or disrupt the Service, or access another customer's data. Don't misrepresent a business in materials you generate. We may suspend accounts that violate these Terms.

## 6. Fees

Current pricing is published on the pricing page. We will give reasonable notice before any change that affects what you pay.

## 7. Termination and your data

You may stop using the Service and request deletion of your account and data at any time via the contact page. We may terminate accounts for violation of these Terms. Upon deletion, your documents, extracted records, and files are removed from our systems within 30 days, excluding legally required retention and short-lived backups.

## 8. Disclaimers

THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE", WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

## 9. Limitation of liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW: (a) WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR LOST PROFITS, LOST BUSINESS VALUE, OR FAILED TRANSACTIONS, EVEN IF ADVISED OF THE POSSIBILITY; AND (b) OUR TOTAL LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE IS LIMITED TO THE GREATER OF $100 OR THE AMOUNTS YOU PAID US IN THE 12 MONTHS BEFORE THE CLAIM AROSE.

Some jurisdictions do not allow certain limitations; in those jurisdictions, these limits apply to the fullest extent permitted.

## 10. Indemnity

You will defend and hold us harmless from claims arising out of your content, your sharing decisions, or your breach of these Terms.

## 11. Changes

We may update these Terms; material changes will be announced in the Service or by email, and continued use after the effective date constitutes acceptance.

## 12. Contact

Questions about these Terms: use [the contact page](/contact).

> note: Plain-English summary — Successio is a documentation tool, not a broker; AI can make mistakes and you must review what it produces before a buyer sees it; you own your data; our liability is capped.
`;

export default function TermsPage() {
  return <LegalPage eyebrow="Legal" title="Terms of Service" updated="July 16, 2026" body={BODY} />;
}
